<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\TeamCollaboration.Application\TeamCollaboration.Application.csproj" />
        <ProjectReference Include="..\TeamCollaboration.Infrastructure\TeamCollaboration.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.10" />
    </ItemGroup>

</Project>
